// automatically generated by admSerialization.py, do not edit!
// automatically generated by admSerialization.py do not edit
#ifndef ADM_denoise3d_CONF_H
#define ADM_denoise3d_CONF_H
typedef struct {
float luma;
float chroma;
float temporal;
}denoise3d;
#endif
